<?php
/**
 * Created by PhpStorm.
 * User: SUN
 * Date: 2018/8/24
 * Time: 15:59
 */

namespace web\mobile\controller;


use think\Request;
use think\Validate;

class Recognize extends Base
{
    private $placementRuleM;
    private $userM;
    private $balanceM;
    private $trandRecordM;
    private $ETD = 13;
    private $RMB = 2;
    private $USDT = 1;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->placementRuleM = new \addons\equity\model\PrivatePlacementRule();
        $this->userM = new \addons\member\model\MemberAccountModel();
        $this->balanceM = new \addons\member\model\Balance();
        $this->trandRecordM = new \addons\member\model\TradingRecord();
    }

    public function index()
    {
        $rule = $this->placementRuleM->find();
        $user = $this->balanceM->where(['user_id' => $this->user_id, 'coin_id' => $this->ETD])->field('amount')->find();

        $data = array(
            'price' => $rule['price'],
            'surplus'   => $rule['gross'],
            'etd_num'   => empty($user['amount']) ? 0 : $user['amount'],
        );

        $this->assign('data',$data);
        return $this->fetch();
    }

    /**
     * 认筹
     */
    public function refer()
    {
        $param = Request::instance()->post();
        $validate = new Validate([
            'num'   => 'require|number|>=:1000'
        ]);
        if(!$validate->check($param))
            return $this->failData($validate->getError());

        $num = $param['num'];

        $rule = $this->placementRuleM->find();
        if($rule['gross'] < $num)
            return $this->failData('剩余认购数量不足');

        $total_price = $rule['price'] * $num;
        $verifyStock = $this->balanceM->verifyStock($this->user_id,$this->USDT,$total_price);
        if(!$verifyStock)
            return $this->failData('USDT余额不足');

        $balanceETD = $this->balanceM->where(['user_id' => $this->user_id, 'coin_id' => $this->ETD])->find();

        $this->placementRuleM->startTrans();
        try
        {
            //认筹数量更新
            $this->placementRuleM->where('id',1)->setDec('gross',$num);

            //用户余额更新
            $this->balanceM->updateBalance($this->user_id,$num,$this->ETD,true);
            $this->balanceM->updateBalance($this->user_id,$total_price,$this->USDT,false);

            //添加交易记录
            $after_amount = $balanceETD['amount'] + $num;
            $this->trandRecordM->addRecord(0,$this->ETD,$num,$balanceETD['amount'],$after_amount,6,1,$this->user_id);

            $this->placementRuleM->commit();
            return $this->successData();
        }catch (\Exception $e)
        {
            $this->placementRuleM->rollback();
        }
    }

    /**
     * 认筹列表
     */
    public function referList()
    {
        $where = array(
            'change_type' => 1,
            'type'  => 6,
        );
        $list = $this->trandRecordM->where($where)->field('to_user_id,amount,update_time')->select();

        return $this->successData($list);
    }
}














