<?php
/**
 * Created by PhpStorm.
 * User: SUN
 * Date: 2018/8/24
 * Time: 11:40
 */

namespace web\mobile\controller;


use think\Request;
use think\Validate;

class Wallet extends Base
{
    private $userM;
    private $payConfM;
    private $balanceM;
    private $USDT = 1;
    private $ETD = 13;
    private $RMB = 2;
    private $privateRuleM;
    private $ethOrderM;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->userM = new \addons\member\model\MemberAccountModel();
        $this->payConfM = new \addons\otc\model\PayConfig();
        $this->balanceM = new \addons\member\model\Balance();
        $this->privateRuleM = new \addons\equity\model\PrivatePlacementRule();
        $this->ethOrderM = new \addons\eth\model\EthTradingOrder();
    }

    public function index()
    {
        $balanceUSDT = $this->balanceM->where(['user_id' => $this->user_id, 'coin_id' => $this->USDT])->find();
        $balanceRMB = $this->balanceM->where(['user_id' => $this->user_id, 'coin_id' => $this->RMB])->find();
        $balanceETD = $this->balanceM->where(['user_id' => $this->user_id, 'coin_id' => $this->ETD])->find();

        $usdt = empty($balanceUSDT['amount']) ? 0 : $balanceUSDT['amount'];
        $rmb = empty($balanceRMB['amount']) ? 0 : bcmul($balanceRMB['amount'],1,2);
        $etd = empty($balanceETD['amount']) ? 0 : $balanceETD['amount'];
        $this->assign('usdt', $usdt);
        $this->assign('rmb', $rmb);
        $this->assign('etd',$etd);
        return $this->fetch();
    }

    public function toSetup()
    {
        return $this->fetch('setup');
    }

    public function toModifyLoginPsw()
    {
        return $this->fetch('modifyloginpsw');
    }

    public function toModifyDealPsw()
    {
        return $this->fetch('modifyDealPsw');
    }

    public function toModifyData()
    {
        $user = $this->userM->where('id',$this->user_id)->field('phone')->find();
        $pay_data = $this->payConfM->where('user_id',$this->user_id)->select();

        $data = array(
            'phone' => $user['phone'],
            'wechat'    => '',
            'alipay'    => '',
            'bank_address'  => '',
            'bank_code' => '',
            'name'  => '',
        );
        foreach ($pay_data as $v)
        {
            switch ($v['type'])
            {
                case 1:
                    $data['wechat'] = $v['account'];
                    break;
                case 2:
                    $data['alipay'] = $v['account'];
                    break;
                case 3:
                    $data['bank_code'] = $v['account'];
                    $data['bank_address'] = $v['bank_address'];
                    $data['name'] = $v['name'];
                    break;
            }
        }

        $this->assign('data',$data);
        return $this->fetch('modifydata');
    }

    public function toInvite()
    {
        $user = $this->userM->getDetail($this->user_id);
        $this->assign('username',$user['username']);
        return $this->fetch('invite');
    }

    /**
     * 修改登录密码
     * @return array
     */
    public function modifyLoginPsw()
    {
        $param = Request::instance()->post();
        $validate = new Validate([
            'password|原密码'  => 'require',
            'new_password|新密码'  => 'require',
            'new_password_confirm'  => 'require|confirm',
        ],[
            'new_password_confirm.confirm'  => '新密码不一致'
        ]);
        if(!$validate->check($param))
            return $this->failData($validate->getError());

        $password = md5($param['password']);
        $new_password = md5($param['new_password']);

        $user = $this->userM->where('id',$this->user_id)->column('password');

        if($user[0] != $password)
            return $this->failData('原密码错误');

        $this->userM->save([
            'password'  => $new_password,
        ],['id' => $this->user_id]);

        return $this->successData();
    }

    /**
     * 修改交易密码
     * @return array
     */
    public function modifyDealPsw()
    {
        $param = Request::instance()->post();
        $validate = new Validate([
            'pay_password|原密码'  => 'require',
            'new_pay_password|新密码'  => 'require',
            'new_pay_password_confirm'  => 'require|confirm',
        ],[
            'new_pay_password_confirm.confirm'  => '新密码不一致'
        ]);
        if(!$validate->check($param))
            return $this->failData($validate->getError());

        $pay_password = md5($param['pay_password']);
        $new_pay_password = md5($param['new_pay_password']);

        $user = $this->userM->where('id',$this->user_id)->column('pay_password');

        if($user[0] != $pay_password)
            return $this->failData('原密码错误');

        $this->userM->save([
            'pay_password'  => $new_pay_password,
        ],['id' => $this->user_id]);

        return $this->successData();
    }

    /**
     * 修改资料
     */
    public function modifyData()
    {
        $param = Request::instance()->post();
        $validate = new Validate([
            'phone' => 'require',
            'alipay'    => 'require',
            'wechat'    => 'require',
            'bank_address'  => 'require',
            'bank_code' => 'require',
            'name'  => 'require',
            'auth_code' => 'require',
            'old_phone' => 'require',
        ]);
        if(!$validate->check($param))
            return $this->failData($validate->getError());

        $old_phone = $param['old_phone'];
        $phone  = $param['phone'];
        $alipay = $param['alipay'];
        $wechat = $param['wechat'];
        $bank_address   = $param['bank_address'];
        $bank_code  = $param['bank_code'];
        $name   = $param['name'];
        $auth_code  = $param['auth_code'];

        $verfyM = new \addons\member\model\VericodeModel();
        $_verify = $verfyM->VerifyCode($auth_code,$old_phone);
        if(empty($_verify))
            return $this->failData('验证码失效，请重新获取');

        $verfyM->startTrans();
        try
        {
            $this->userM->save([
                'phone' => $phone,
            ],['id' => $this->user_id]);

            $this->payConfM->save([
                'account' => $wechat,
            ],[
                'user_id'   => $this->user_id,
                'type'      => 1
            ]);

            $this->payConfM->save([
                'account'   => $alipay,
            ],[
                'user_id'   => $this->user_id,
                'type'      => 2
            ]);

            $this->payConfM->save([
                'bank_address'  => $bank_address,
                'account'   => $bank_code,
                'name'      => $name,
            ],[
                'user_id'   => $this->user_id,
                'type'  => 3
            ]);

            $verfyM->commit();
            return $this->successData();
        }catch (\Exception $e)
        {
            $verfyM->rollback();
            return $this->failData($e->getMessage());
        }

    }

    public function toWithdrawUSDT()
    {
        $balance = $this->balanceM->where(['user_id' => $this->user_id, 'coin_id' => $this->USDT])->find();

        $usdt_num = empty($balance['amount']) ? 0 : $balance['amount'];
        $this->assign('usdt_num',$usdt_num);
        return $this->fetch('withdrawUSDT');
    }

    public function withdrawUSDT()
    {
        $param = Request::instance()->post();
        $validate = new Validate([
            'address'   => 'require',
            'num'       => 'require',
            'pay_password'  => 'require',
        ]);
        if(!$validate->check($param))
            return $this->failData($validate->getError());

        $address = $param['address'];
        $num = $param['num'];
        $pay_password = md5($param['pay_password']);

        $balanceM = new \addons\member\model\Balance();
        $verify = $balanceM->verifyStock($this->user_id,$this->USDT,$num);
        if(!$verify)
            return $this->failData('USDT余额不足');

        $user = $this->userM->getDetail($this->user_id);
        if($user['pay_password'] != $pay_password)
            return $this->failData('密码错误');

        $balance = $balanceM->where(['user_id' => $this->user_id, 'coin_id' => $this->ETD])->find();
        $privateRule = $this->privateRuleM->find();

        $balanceM->startTrans();
        try
        {
            //余额更新
            $this->balanceM->updateBalance($this->user_id,$num,$this->USDT,false);
            //添加交易记录
            $recordM = new \addons\member\model\TradingRecord();
            $after_amount = $balance['amount'] - $num;
            $recordM->addRecord($this->user_id,$this->USDT,$num,$balance['amount'],$after_amount,3,0,'',$address);

            //添加USDT转账订单记录
            $usdtOrderM = new \addons\eth\model\EthTradingOrder();
            $data = array(
                'user_id'   => $this->user_id,
                'coin_id'   => $this->USDT,
//                'txhash'    => $this->getHash(),
                'from_address'  => $user['address'],
                'to_address'    => $address,
                'type'      => 0,
                'status'    => 0,
                'amount'    => $num,
                'update_time'    => NOW_DATETIME,
            );
            $usdtOrderM->save($data);

            $balanceM->commit();
            return $this->successData();
        }catch (\Exception $e)
        {
            $balanceM->rollback();
            return $this->failData($e->getMessage());
        }
    }

    private function getHash()
    {
        $chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()+-';
        $random = $chars[mt_rand(0,73)].$chars[mt_rand(0,73)].$chars[mt_rand(0,73)].$chars[mt_rand(0,73)];
        $content = uniqid().$random;

        return sha1($content);
    }

    public function toWithdrawList()
    {
        return $this->fetch('withdrawList');
    }

    public function withdrawList()
    {
        $param = Request::instance()->post();
        $validate = new Validate([
            'coin_id'  => 'require',
        ]);

        if(!$validate->check($param))
            return $this->failData($validate->getError());

        $data = $this->ethOrderM->where(['user_id' => $this->user_id, 'coin_id' => $param['coin_id'],'type' => 0])->field('amount,type,status,update_time,to_address')->select();
        for($i = 0; $i < count($data); $i++)
        {
            switch ($data[$i]['status'])
            {
                case 0:
                    $data[$i]['status'] = '未审核';    break;
                case 1:
                    $data[$i]['status'] = '已完成';    break;
                case 4:
                    $data[$i]['status'] = '未通过';    break;
            }
        }

        return $this->successData($data);
    }

    public function toAddress()
    {
        $user = $this->userM->getDetail($this->user_id);
        $this->assign('address',$user['address']);
        return $this->fetch('address');
    }
}
















